# 服务器配置
server:
  port: 8080  # 应用服务端口

# Spring相关配置
spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/realtime_stats?useSSL=false&serverTimezone=UTC  # 数据库连接URL
    username: root  # 数据库用户名
    password: 123456  # 数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver  # JDBC驱动类
    
    # Hikari连接池配置
    hikari:
      pool-name: HikariCP  # 连接池名称
      maximum-pool-size: 10  # 最大连接数
      minimum-idle: 5  # 最小空闲连接
      connection-timeout: 30000  # 连接超时时间(毫秒)
      idle-timeout: 600000  # 空闲连接超时时间(毫秒)
      max-lifetime: 1800000  # 连接最大生命周期(毫秒)

  # Redis配置
  redis:
    host: localhost  # Redis服务器地址
    port: 6379  # Redis端口
    password:  # Redis密码(无密码留空)
    database: 0  # Redis数据库索引

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 启用控制台SQL日志输出
    map-underscore-to-camel-case: true  # 开启下划线转驼峰
  global-config:
    db-config:
      id-type: auto  # ID生成策略:数据库自增
      logic-delete-field: deleted  # 逻辑删除字段名
      logic-not-delete-value: 0  # 未删除值
      logic-delete-value: 1  # 删除值

# 实时统计自定义配置
realtime-stats:
  redis-key-prefix:
    content: "content:"  # 内容相关key前缀
    like: "like:"  # 点赞相关key前缀
    pageView: "pv:"  # 页面浏览相关key前缀
    uniqueVisitor: "uv:"  # 独立访客相关key前缀
    gamePlayer: "gp:"  # 游戏玩家相关key前缀
    hotSearch: "hs:"  # 热搜相关key前缀
  
  sync:
    interval: 300000  # 同步间隔时间(毫秒)
    batchSize: 100  # 批量同步大小
  
# 日志配置
logging:
  level:
    org.springframework: INFO  # Spring框架日志级别
    org.example: DEBUG  # 项目代码日志级别
    com.baomidou.mybatisplus: DEBUG  # MyBatis-Plus日志级别
